import type { Card, Noble } from '../types/game';

// 개발 카드 - 레벨 1 (40장)
const level1Cards: Omit<Card, 'id'>[] = [
  { level: 1, color: 'green',  points: 0, cost: { green: 1, white: 0, blue: 1, black: 1, red: 0 } },
  { level: 1, color: 'white',  points: 1, cost: { green: 4, white: 0, blue: 0, black: 0, red: 0 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 0, white: 3, blue: 0, black: 0, red: 0 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 1, white: 1, blue: 0, black: 1, red: 1 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 3, white: 0, blue: 1, black: 0, red: 1 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 0, white: 1, blue: 0, black: 2, red: 0 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 0, white: 0, blue: 3, black: 0, red: 0 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 1, white: 2, blue: 0, black: 2, red: 0 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 0, white: 1, blue: 0, black: 3, red: 1 } },
  { level: 1, color: 'green',  points: 0, cost: { green: 0, white: 0, blue: 1, black: 2, red: 2 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 1, white: 2, blue: 1, black: 1, red: 0 } },
  { level: 1, color: 'green',  points: 0, cost: { green: 0, white: 0, blue: 2, black: 0, red: 2 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 2, white: 0, blue: 0, black: 2, red: 0 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 1, white: 1, blue: 0, black: 1, red: 2 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 0, white: 2, blue: 2, black: 0, red: 1 } },
  { level: 1, color: 'green',  points: 1, cost: { green: 0, white: 0, blue: 0, black: 4, red: 0 } },
  { level: 1, color: 'green',  points: 0, cost: { green: 0, white: 1, blue: 1, black: 1, red: 1 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 1, white: 1, blue: 1, black: 1, red: 0 } },
  { level: 1, color: 'red',    points: 1, cost: { green: 0, white: 4, blue: 0, black: 0, red: 0 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 0, white: 2, blue: 0, black: 0, red: 2 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 2, white: 0, blue: 1, black: 1, red: 1 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 0, white: 0, blue: 2, black: 2, red: 0 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 0, white: 3, blue: 1, black: 1, red: 0 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 2, white: 1, blue: 0, black: 0, red: 2 } },
  { level: 1, color: 'blue',   points: 1, cost: { green: 0, white: 0, blue: 0, black: 0, red: 4 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 1, white: 1, blue: 1, black: 0, red: 1 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 3, white: 0, blue: 0, black: 0, red: 0 } },
  { level: 1, color: 'red',    points: 0, cost: { green: 1, white: 0, blue: 2, black: 0, red: 0 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 0, white: 0, blue: 0, black: 1, red: 2 } },
  { level: 1, color: 'green',  points: 0, cost: { green: 0, white: 2, blue: 1, black: 0, red: 0 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 1, white: 1, blue: 2, black: 0, red: 1 } },
  { level: 1, color: 'green',  points: 0, cost: { green: 1, white: 1, blue: 3, black: 0, red: 0 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 2, white: 0, blue: 2, black: 1, red: 0 } },
  { level: 1, color: 'white',  points: 0, cost: { green: 1, white: 0, blue: 1, black: 1, red: 1 } },
  { level: 1, color: 'black',  points: 1, cost: { green: 0, white: 0, blue: 4, black: 0, red: 0 } },
  { level: 1, color: 'green',  points: 0, cost: { green: 0, white: 0, blue: 0, black: 0, red: 3 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 2, white: 2, blue: 0, black: 0, red: 0 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 2, white: 0, blue: 0, black: 0, red: 1 } },
  { level: 1, color: 'black',  points: 0, cost: { green: 1, white: 0, blue: 0, black: 1, red: 3 } },
  { level: 1, color: 'blue',   points: 0, cost: { green: 0, white: 0, blue: 0, black: 3, red: 0 } },
];

// 개발 카드 - 레벨 2 (30장)
const level2Cards: Omit<Card, 'id'>[] = [
  { level: 2, color: 'red',    points: 2, cost: { green: 0, white: 0, blue: 0, black: 5, red: 0 } },
  { level: 2, color: 'white',  points: 2, cost: { green: 0, white: 0, blue: 0, black: 3, red: 5 } },
  { level: 2, color: 'black',  points: 3, cost: { green: 0, white: 0, blue: 0, black: 6, red: 0 } },
  { level: 2, color: 'green',  points: 1, cost: { green: 2, white: 3, blue: 0, black: 0, red: 3 } },
  { level: 2, color: 'red',    points: 1, cost: { green: 0, white: 2, blue: 0, black: 3, red: 2 } },
  { level: 2, color: 'green',  points: 2, cost: { green: 0, white: 4, blue: 2, black: 1, red: 0 } },
  { level: 2, color: 'white',  points: 1, cost: { green: 0, white: 2, blue: 3, black: 0, red: 3 } },
  { level: 2, color: 'blue',   points: 1, cost: { green: 2, white: 0, blue: 2, black: 0, red: 3 } },
  { level: 2, color: 'blue',   points: 2, cost: { green: 0, white: 5, blue: 3, black: 0, red: 0 } },
  { level: 2, color: 'black',  points: 1, cost: { green: 2, white: 3, blue: 2, black: 0, red: 0 } },
  { level: 2, color: 'black',  points: 2, cost: { green: 0, white: 5, blue: 0, black: 0, red: 0 } },
  { level: 2, color: 'green',  points: 2, cost: { green: 3, white: 0, blue: 5, black: 0, red: 0 } },
  { level: 2, color: 'white',  points: 1, cost: { green: 3, white: 0, blue: 0, black: 2, red: 2 } },
  { level: 2, color: 'blue',   points: 2, cost: { green: 0, white: 2, blue: 0, black: 4, red: 1 } },
  { level: 2, color: 'red',    points: 2, cost: { green: 2, white: 1, blue: 4, black: 0, red: 0 } },
  { level: 2, color: 'red',    points: 2, cost: { green: 0, white: 3, blue: 0, black: 5, red: 0 } },
  { level: 2, color: 'blue',   points: 1, cost: { green: 3, white: 0, blue: 2, black: 3, red: 0 } },
  { level: 2, color: 'white',  points: 2, cost: { green: 1, white: 0, blue: 0, black: 2, red: 4 } },
  { level: 2, color: 'white',  points: 2, cost: { green: 0, white: 0, blue: 0, black: 0, red: 5 } },
  { level: 2, color: 'red',    points: 1, cost: { green: 0, white: 0, blue: 3, black: 3, red: 2 } },
  { level: 2, color: 'green',  points: 2, cost: { green: 5, white: 0, blue: 0, black: 0, red: 0 } },
  { level: 2, color: 'green',  points: 1, cost: { green: 0, white: 2, blue: 3, black: 2, red: 0 } },
  { level: 2, color: 'green',  points: 3, cost: { green: 6, white: 0, blue: 0, black: 0, red: 0 } },
  { level: 2, color: 'red',    points: 3, cost: { green: 0, white: 0, blue: 0, black: 0, red: 6 } },
  { level: 2, color: 'black',  points: 2, cost: { green: 5, white: 0, blue: 0, black: 0, red: 3 } },
  { level: 2, color: 'blue',   points: 3, cost: { green: 0, white: 0, blue: 6, black: 0, red: 0 } },
  { level: 2, color: 'white',  points: 3, cost: { green: 0, white: 6, blue: 0, black: 0, red: 0 } },
  { level: 2, color: 'blue',   points: 2, cost: { green: 0, white: 0, blue: 5, black: 0, red: 0 } },
  { level: 2, color: 'black',  points: 1, cost: { green: 3, white: 3, blue: 0, black: 2, red: 0 } },
  { level: 2, color: 'black',  points: 2, cost: { green: 4, white: 0, blue: 1, black: 0, red: 2 } },
];

// 개발 카드 - 레벨 3 (20장)
const level3Cards: Omit<Card, 'id'>[] = [
  { level: 3, color: 'white',  points: 3, cost: { green: 3, white: 0, blue: 3, black: 3, red: 5 } },
  { level: 3, color: 'black',  points: 4, cost: { green: 3, white: 0, blue: 0, black: 3, red: 6 } },
  { level: 3, color: 'blue',   points: 4, cost: { green: 0, white: 7, blue: 0, black: 0, red: 0 } },
  { level: 3, color: 'blue',   points: 4, cost: { green: 0, white: 6, blue: 3, black: 3, red: 0 } },
  { level: 3, color: 'green',  points: 4, cost: { green: 3, white: 3, blue: 6, black: 0, red: 0 } },
  { level: 3, color: 'green',  points: 3, cost: { green: 0, white: 5, blue: 3, black: 3, red: 3 } },
  { level: 3, color: 'blue',   points: 3, cost: { green: 3, white: 3, blue: 0, black: 5, red: 3 } },
  { level: 3, color: 'red',    points: 3, cost: { green: 3, white: 3, blue: 5, black: 3, red: 0 } },
  { level: 3, color: 'blue',   points: 5, cost: { green: 0, white: 7, blue: 3, black: 0, red: 0 } },
  { level: 3, color: 'white',  points: 4, cost: { green: 0, white: 0, blue: 0, black: 7, red: 0 } },
  { level: 3, color: 'red',    points: 4, cost: { green: 6, white: 0, blue: 3, black: 0, red: 3 } },
  { level: 3, color: 'black',  points: 3, cost: { green: 5, white: 3, blue: 3, black: 0, red: 3 } },
  { level: 3, color: 'black',  points: 4, cost: { green: 0, white: 0, blue: 0, black: 0, red: 7 } },
  { level: 3, color: 'white',  points: 5, cost: { green: 0, white: 3, blue: 0, black: 7, red: 0 } },
  { level: 3, color: 'white',  points: 4, cost: { green: 0, white: 3, blue: 0, black: 6, red: 3 } },
  { level: 3, color: 'red',    points: 5, cost: { green: 7, white: 0, blue: 0, black: 0, red: 3 } },
  { level: 3, color: 'red',    points: 4, cost: { green: 7, white: 0, blue: 0, black: 0, red: 0 } },
  { level: 3, color: 'green',  points: 4, cost: { green: 0, white: 0, blue: 7, black: 0, red: 0 } },
  { level: 3, color: 'black',  points: 5, cost: { green: 0, white: 0, blue: 0, black: 3, red: 7 } },
  { level: 3, color: 'green',  points: 5, cost: { green: 3, white: 0, blue: 7, black: 0, red: 0 } },
];

// 귀족 타일 (10장) - 배열 순서: [green, white, blue, black, red]
const nobleData: Omit<Noble, 'id'>[] = [
  { points: 3, requirement: { green: 4, white: 0, blue: 4, black: 0, red: 0 } },
  { points: 3, requirement: { green: 0, white: 0, blue: 0, black: 4, red: 4 } },
  { points: 3, requirement: { green: 3, white: 3, blue: 3, black: 0, red: 0 } },
  { points: 3, requirement: { green: 0, white: 3, blue: 0, black: 3, red: 3 } },
  { points: 3, requirement: { green: 0, white: 4, blue: 0, black: 4, red: 0 } },
  { points: 3, requirement: { green: 4, white: 0, blue: 0, black: 0, red: 4 } },
  { points: 3, requirement: { green: 0, white: 4, blue: 4, black: 0, red: 0 } },
  { points: 3, requirement: { green: 3, white: 0, blue: 3, black: 0, red: 3 } },
  { points: 3, requirement: { green: 3, white: 0, blue: 0, black: 3, red: 3 } },
  { points: 3, requirement: { green: 0, white: 3, blue: 3, black: 3, red: 0 } },
];

// id 붙여서 export
export const ALL_CARDS: Card[] = [
  ...level1Cards,
  ...level2Cards,
  ...level3Cards,
].map((card, i) => ({ ...card, id: `card-${i}` }));

export const ALL_NOBLES: Noble[] = nobleData.map((noble, i) => ({
  ...noble,
  id: `noble-${i}`,
}));
